<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{83f4e28e-4703-460b-98e7-32d6d206e679}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

	//备注测试
	
	
	PRG_TEST();
	]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="1" />
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>