<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PRG_TEST" Id="{55b693b2-7ec3-4123-bf43-681ce4807bf9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>